### ISSUE TITLE
"As a user, I want to see indicators listed in the goal pages so that I can browse through available indicators I can view"

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/unkt-sdg-plugin#3] opened 2017-01-05 13:40 UTC

**Comment by dafinaolluri** [comment] 2017-01-05 13:41
Acceptance Criteria

**Comment by georgeslabreche** [comment] 2017-01-11 16:25
@dafinaolluri @partini @artaabdullahu this is not accepted because 1) the issue isn't associated with a milestone and 2) nobody is assigned to it.

**Comment by georgeslabreche** [comment] 2017-01-11 16:36
@dafinaolluri @partini @artaabdullahu turns out this was just a test issue. Closing it.

**Closed as completed by georgeslabreche** 2017-01-11 16:36 UTC
