### ISSUE TITLE
As a user I want to have 17 SDG Icons so I can easily navigate to specific goals by clicking on an icon.

### ISSUE THREAD

**Issue by partini** [opendatakosovo/unkt-sdg-plugin#10] opened 2017-01-11 13:06 UTC
Description:
Each clicked icon brings us to an empty SDG Goal page.

Acceptance Criteria:
- [x] Each clicked icon brings us to an empty SDG Goal page.

**Comment by georgeslabreche** [comment] 2017-01-11 16:25
@dafinaolluri @partini @artaabdullahu this is not accepted because 1) the issue isn't associated with a milestone and 2) nobody is assigned to it.

**Closed as completed** 2017-03-02 10:45 UTC
Labels: problem with plugin
